[project]
name = "skadi"
version = "0.1.0"
description = "Manipulate quantum circuits using natural language"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "pennylane>=0.43.1",
]
